### ISSUE TITLE
Has the access to the API been closed down?

### ISSUE THREAD

**Issue by joao** [shrunbr/cloudflare-radar#1]
Hi @shrunbr!

Followed the instructions, using as the first request the 'GET Categories' to set a token, but it just returns an HTML DDoS error from Cloudflare.

Does it still work for you or has access been limited, since you first wrote these endpoints collection?

Thank you!

**Comment by shrunbr** [comment]
Hi @joao,

I briefly used this for about a week after I posted this. I think that Cloudflare is doing some sort of checks for automation, I also check radar and noticed that some of the endpoints changed. I don't think this is worth pursing at this time. I'll mark the repo as such and archive it.

Sorry :/
